---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1776447/public_html/
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp service.html $DEPLOYPATH
    - /bin/cp indeks.html $DEPLOYPATH
    - /bin/cp servis.html $DEPLOYPATH
    - /bin/cp galeri.html $DEPLOYPATH
    - /bin/cp kontak.html $DEPLOYPATH
    - /bin/cp tentang.html $DEPLOYPATH
    - /bin/cp sitemap.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R project $DEPLOYPATH
    - /bin/cp /project/10m_ambulance.html $DEPLOYPATH
    - /bin/cp /project/10m_ambulance.css $DEPLOYPATH
    - /bin/cp /project/11mspeed.html $DEPLOYPATH
    - /bin/cp /project/11mspeed.css $DEPLOYPATH
    - /bin/cp /project/12m_ambulance.html $DEPLOYPATH
    - /bin/cp /project/12m_ambulance.css $DEPLOYPATH
    - /bin/cp /project/13mpass.html $DEPLOYPATH
    - /bin/cp /project/13mpass.css $DEPLOYPATH
    - /bin/cp /project/14mspeed.html $DEPLOYPATH
    - /bin/cp /project/14mspeed.css $DEPLOYPATH
    - /bin/cp /project/15mpleasure.html $DEPLOYPATH
    - /bin/cp /project/15mpleasure.css $DEPLOYPATH
    - /bin/cp /project/glassbottom.html $DEPLOYPATH
    - /bin/cp /project/glassbottom.css $DEPLOYPATH
    - /bin/cp /project/rbb.html $DEPLOYPATH
    - /bin/cp /project/rbb.css $DEPLOYPATH
    - /bin/cp /project/wooden.html $DEPLOYPATH
    - /bin/cp /project/wooden.css $DEPLOYPATH
